linters:
  enable:
    - asciicheck # Simple linter to check that your code does not contain non-ASCII identifiers.
    - gci # Control golang package import order and make it always deterministic.
    - godot # Check if comments end in a period.
    - misspell # Finds commonly misspelled English words in comments.
    - gofumpt
